# Generated by Django 3.2.9 on 2021-11-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_comments_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_name',
            field=models.CharField(default='Mike', max_length=100, null=True),
        ),
    ]
