# Generated by Django 3.2.9 on 2021-11-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(blank=True, default='users-profiles/default-avatar.png', null=True, upload_to='img/users-profiles'),
        ),
    ]
