# Generated by Django 3.2.9 on 2021-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_alter_profile_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_profile',
            field=models.CharField(default='users-profiles/default-avatar.png', max_length=120, null=True),
        ),
    ]
